### ISSUE TITLE
0.1 Cocoon 🌷

### ISSUE THREAD

**Issue by eerii** [josekoalas/lume#19]
- [x] 0.1.1 Fresa #28 
- [x] 0.1.2 New Rendering Pipeline #29 
- [x] 0.1.3 Serialization #30 
- [x] 0.1.4 Procedural Animation #32 
- [x] 0.1.5 Fixes and State Machine #33
- [x] 0.1.6 Scene Transitions #31 
- [x] 0.1.7 Water #22
- [x] 0.1.8 State and Animation #34
- [x] 0.1.9 Web #35 
- [x] 0.1.10 Light #23
- [x] 0.1.11 Editor #36 
- [x] 0.1.12 Platforms #21 
- [x] 0.1.12b Camera #37 
- [x] 0.1.13 Text #38 
- [x] 0.1.14 Tiny Things #39 
- [x] 0.1.15 Vulkan #40 

After this stage is done, release a playtest version of the first levels and mechanics before adding enemies to test how everything goes, the feel, what works and what doesn't, and to balance everything out.
